-- INERGO · 103 retos de serie (mismos ids que en la app, para conservar
-- historiales, pendientes y retos desactivados de los usuarios).
-- Se puede ejecutar varias veces: no duplica ni pisa cambios.
insert into public.challenges (id, text, category, duration_type, duration_seconds, research_seconds, talk_seconds, points, active, sort_order) values
  ('espontanea-001', 'Sal a la calle ahora mismo y hazle un cumplido sincero y específico a 3 desconocidos, grabando su reacción.', 'espontanea', 'timer', 900, null, null, 20, true, 10),
  ('espontanea-002', 'Entra en una tienda y pide un descuento sin ningún motivo real, solo porque sí.', 'espontanea', 'timer', 300, null, null, 20, true, 20),
  ('espontanea-003', 'Pide un abrazo a un desconocido por la calle, tras hablar con él.', 'espontanea', 'timer', 420, null, null, 20, true, 30),
  ('espontanea-004', 'Llama ahora mismo a alguien con quien no hablas hace tiempo y dile en voz alta por qué te importó.', 'espontanea', 'timer', 600, null, null, 20, true, 40),
  ('espontanea-005', 'Mirando fijamente a cámara, confiesa algo que te avergüenza y que nunca has contado a nadie.', 'espontanea', 'timer', 300, null, null, 20, true, 50),
  ('espontanea-006', 'Pregunta a un desconocido cuál es su mayor arrepentimiento en la vida.', 'espontanea', 'timer', 480, null, null, 20, true, 60),
  ('espontanea-007', 'Entra en una tienda de ropa que nunca pisarías, pruébate algo y pide la opinión sincera a un desconocido dentro del probador.', 'espontanea', 'timer', 900, null, null, 20, true, 70),
  ('espontanea-008', 'Pide en un bar o restaurante que te recomienden algo "para impresionar a alguien" y cuéntales por qué lo necesitas.', 'espontanea', 'timer', 600, null, null, 20, true, 80),
  ('espontanea-009', 'Pide a un desconocido que te haga una crítica honesta de tu outfit de hoy.', 'espontanea', 'timer', 300, null, null, 20, true, 90),
  ('espontanea-010', 'Ve a la sección de perfumería o cosmética de una tienda y pide a un dependiente que te maquille o te ponga colonia mientras la gente mira.', 'espontanea', 'timer', 900, null, null, 20, true, 100),
  ('espontanea-011', 'Pide a alguien random que pasa por la calle que te dé un consejo de vida en 30 segundos.', 'espontanea', 'timer', 300, null, null, 20, true, 110),
  ('espontanea-012', 'Pide a un grupo de desconocidos que se echen una foto contigo sin dar ninguna razón.', 'espontanea', 'timer', 480, null, null, 20, true, 120),
  ('espontanea-013', 'Aprende qué es un suceso, un concepto científico o algo muy nicho de una disciplina que no domines, y explícalo sin muletillas durante 1 minuto. Tienes 20 minutos para investigarlo y grabarte explicándolo.', 'espontanea', 'timer', 1200, null, null, 20, true, 130),
  ('experiencia-001', 'Ve a un pueblo o barrio a menos de 15 minutos de donde vives, cena allí completamente solo y date una vuelta.', 'experiencia', 'pending', null, null, null, 50, true, 140),
  ('experiencia-002', 'Ve solo al cine a la sesión con el horario más raro que encuentres y cuenta cómo te sentiste al salir.', 'experiencia', 'pending', null, null, null, 50, true, 150),
  ('experiencia-003', 'Haz autostop real o pide ayuda a un desconocido para resolver algo que necesitas hoy.', 'experiencia', 'pending', null, null, null, 50, true, 160),
  ('experiencia-004', 'Preséntate en persona (sin cita previa) en un sitio donde te gustaría trabajar o colaborar, y pide hablar con alguien.', 'experiencia', 'pending', null, null, null, 50, true, 170),
  ('experiencia-005', 'Sal de tu ciudad un día entero sin planear nada: elige destino la misma mañana.', 'experiencia', 'pending', null, null, null, 50, true, 180),
  ('experiencia-006', 'Cuenta tu mayor miedo en voz alta a un grupo de amigos reunidos, sin quitarle importancia después.', 'experiencia', 'pending', null, null, null, 50, true, 190),
  ('experiencia-007', 'Ve solo a un evento social donde no conozcas a nadie y no te vayas hasta haber hablado con 3 personas nuevas.', 'experiencia', 'pending', null, null, null, 50, true, 200),
  ('experiencia-008', 'Pide trabajo temporal de un día (ayudar en un negocio, repartir, lo que sea) tocando puertas sin experiencia previa en ello.', 'experiencia', 'pending', null, null, null, 50, true, 210),
  ('experiencia-009', 'Pasa 24 horas comiendo únicamente lo que te recomiende gente random que pares por la calle.', 'experiencia', 'pending', null, null, null, 50, true, 220),
  ('experiencia-010', 'Levántate mañana antes del amanecer, ve a verlo y grábalo.', 'experiencia', 'pending', null, null, null, 50, true, 230),
  ('reflexion-001', 'Reflexiona en voz alta sobre: el miedo al fracaso.', 'reflexion', 'timer', 60, null, null, 15, true, 240),
  ('reflexion-002', 'Reflexiona en voz alta sobre: el miedo a lo que piensan los demás de ti.', 'reflexion', 'timer', 60, null, null, 15, true, 250),
  ('reflexion-003', 'Reflexiona en voz alta sobre: la última vez que mentiste, y por qué.', 'reflexion', 'timer', 60, null, null, 15, true, 260),
  ('reflexion-004', 'Reflexiona en voz alta sobre: algo que te arrepientes de no haber dicho.', 'reflexion', 'timer', 60, null, null, 15, true, 270),
  ('reflexion-005', 'Reflexiona en voz alta sobre: tu mayor inseguridad física.', 'reflexion', 'timer', 60, null, null, 15, true, 280),
  ('reflexion-006', 'Reflexiona en voz alta sobre: la persona a la que más admiras, y por qué.', 'reflexion', 'timer', 60, null, null, 15, true, 290),
  ('reflexion-007', 'Reflexiona en voz alta sobre: el día que más miedo has pasado en tu vida.', 'reflexion', 'timer', 60, null, null, 15, true, 300),
  ('reflexion-008', 'Reflexiona en voz alta sobre: algo que finges que no te importa, pero sí te importa.', 'reflexion', 'timer', 60, null, null, 15, true, 310),
  ('reflexion-009', 'Reflexiona en voz alta sobre: lo que harías si supieras que no vas a fracasar.', 'reflexion', 'timer', 60, null, null, 15, true, 320),
  ('reflexion-010', 'Reflexiona en voz alta sobre: la relación que más te ha marcado, para bien o para mal.', 'reflexion', 'timer', 60, null, null, 15, true, 330),
  ('reflexion-011', 'Reflexiona en voz alta sobre: qué es el éxito para ti, de verdad.', 'reflexion', 'timer', 60, null, null, 15, true, 340),
  ('reflexion-012', 'Reflexiona en voz alta sobre: algo que le dirías a tu yo de hace 5 años.', 'reflexion', 'timer', 60, null, null, 15, true, 350),
  ('reflexion-013', 'Reflexiona en voz alta sobre: el motivo real por el que procrastinas.', 'reflexion', 'timer', 60, null, null, 15, true, 360),
  ('reflexion-014', 'Reflexiona en voz alta sobre: qué harías si solo te quedara un año de vida.', 'reflexion', 'timer', 60, null, null, 15, true, 370),
  ('reflexion-015', 'Reflexiona en voz alta sobre: cómo te afecta compararte con otros.', 'reflexion', 'timer', 60, null, null, 15, true, 380),
  ('reflexion-016', 'Reflexiona en voz alta sobre: un error que cambió tu forma de ver la vida.', 'reflexion', 'timer', 60, null, null, 15, true, 390),
  ('reflexion-017', 'Reflexiona en voz alta sobre: qué es lo que más evitas sentir.', 'reflexion', 'timer', 60, null, null, 15, true, 400),
  ('reflexion-018', 'Reflexiona en voz alta sobre: tu relación con el dinero.', 'reflexion', 'timer', 60, null, null, 15, true, 410),
  ('reflexion-019', 'Reflexiona en voz alta sobre: lo que de verdad piensas de la muerte.', 'reflexion', 'timer', 60, null, null, 15, true, 420),
  ('reflexion-020', 'Reflexiona en voz alta sobre: algo que llevas mucho tiempo posponiendo, y por qué.', 'reflexion', 'timer', 60, null, null, 15, true, 430),
  ('conocimiento-001', 'Investiga qué es la xantopsia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 440),
  ('conocimiento-002', 'Investiga qué es la cataplejía y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 450),
  ('conocimiento-003', 'Investiga qué es la anosognosia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 460),
  ('conocimiento-004', 'Investiga qué es la acalasia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 470),
  ('conocimiento-005', 'Investiga qué es la miosis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 480),
  ('conocimiento-006', 'Investiga qué es la aloimunización y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 490),
  ('conocimiento-007', 'Investiga qué es la xerostomía y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 500),
  ('conocimiento-008', 'Investiga qué es la disautonomía y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 510),
  ('conocimiento-009', 'Investiga qué es la paramnesia reduplicativa y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 520),
  ('conocimiento-010', 'Investiga qué es la coprolalia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 530),
  ('conocimiento-011', 'Investiga qué es el efecto Mpemba y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 540),
  ('conocimiento-012', 'Investiga qué es la superfluidez y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 550),
  ('conocimiento-013', 'Investiga qué es la radiación de Cherenkov y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 560),
  ('conocimiento-014', 'Investiga qué es el punto triple de una sustancia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 570),
  ('conocimiento-015', 'Investiga qué es el efecto Casimir y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 580),
  ('conocimiento-016', 'Investiga qué es el efecto Leidenfrost y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 590),
  ('conocimiento-017', 'Investiga qué es el diamagnetismo y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 600),
  ('conocimiento-018', 'Investiga qué es el efecto Coriolis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 610),
  ('conocimiento-019', 'Investiga qué es la superconductividad y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 620),
  ('conocimiento-020', 'Investiga qué es el efecto túnel cuántico y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 630),
  ('conocimiento-021', 'Investiga qué es la partenogénesis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 640),
  ('conocimiento-022', 'Investiga qué es la mixotrofia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 650),
  ('conocimiento-023', 'Investiga qué es la diapausa y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 660),
  ('conocimiento-024', 'Investiga qué es la endosimbiosis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 670),
  ('conocimiento-025', 'Investiga qué es la alelopatía y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 680),
  ('conocimiento-026', 'Investiga qué es la apoptosis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 690),
  ('conocimiento-027', 'Investiga qué es la quimiotaxis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 700),
  ('conocimiento-028', 'Investiga qué es la micorriza y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 710),
  ('conocimiento-029', 'Investiga qué es la criptobiosis y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 720),
  ('conocimiento-030', 'Investiga qué es el epifitismo y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 730),
  ('conocimiento-031', 'Investiga qué es un piroclasto y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 740),
  ('conocimiento-032', 'Investiga qué es el relieve kárstico y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 750),
  ('conocimiento-033', 'Investiga qué es una diaclasa y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 760),
  ('conocimiento-034', 'Investiga qué es la isostasia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 770),
  ('conocimiento-035', 'Investiga qué es la tefra y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 780),
  ('conocimiento-036', 'Investiga qué es un xenolito y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 790),
  ('conocimiento-037', 'Investiga qué es la estratigrafía y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 800),
  ('conocimiento-038', 'Investiga qué es la subducción de placas y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 810),
  ('conocimiento-039', 'Investiga qué es un lacolito y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 820),
  ('conocimiento-040', 'Investiga qué son las varvas y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 830),
  ('conocimiento-041', 'Investiga qué es la apofenia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 840),
  ('conocimiento-042', 'Investiga qué es el efecto Zeigarnik y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 850),
  ('conocimiento-043', 'Investiga qué es la criptomnesia y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 860),
  ('conocimiento-044', 'Investiga qué es el efecto Barnum y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 870),
  ('conocimiento-045', 'Investiga qué es el condicionamiento clásico de Pavlov y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 880),
  ('conocimiento-046', 'Investiga qué es el efecto halo y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 890),
  ('conocimiento-047', 'Investiga qué es la disonancia cognitiva y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 900),
  ('conocimiento-048', 'Investiga qué es el efecto Pigmalión y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 910),
  ('conocimiento-049', 'Investiga qué es el sesgo de anclaje y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 920),
  ('conocimiento-050', 'Investiga qué es el efecto espectador y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 930),
  ('conocimiento-051', 'Investiga en qué consistió el Cisma de Occidente y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 940),
  ('conocimiento-052', 'Investiga en qué consistió la Guerra de la Oreja de Jenkins y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 950),
  ('conocimiento-053', 'Investiga en qué consistió la Peste de Justiniano y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 960),
  ('conocimiento-054', 'Investiga en qué consistió el Incidente de Mukden y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 970),
  ('conocimiento-055', 'Investiga en qué consistió la Rebelión de los Bóxers y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 980),
  ('conocimiento-056', 'Investiga en qué consistió el Tratado de Tordesillas y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 990),
  ('conocimiento-057', 'Investiga en qué consistió la Matanza de Katyn y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 1000),
  ('conocimiento-058', 'Investiga en qué consistió la Defenestración de Praga y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 1010),
  ('conocimiento-059', 'Investiga en qué consistió el Cisma de 1054 entre las Iglesias católica y ortodoxa y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 1020),
  ('conocimiento-060', 'Investiga en qué consistió la Guerra de las Comunidades de Castilla y prepárate para explicarlo.', 'conocimiento', 'research', null, 600, 60, 20, true, 1030)
on conflict (id) do nothing;
